import { readFile, writeFile, readdir, mkdir, access } from "fs/promises";
import { join } from "path";

interface ServiceEntry {
  name: string;
  purpose: string;
  location: string;
  category: string;
}

/**
 * Parse a CONTEXT.md file to extract name and purpose.
 */
function parseContextMd(content: string): { name: string; purpose: string } | null {
  // Extract name from first H1
  const nameMatch = content.match(/^#\s+(.+)$/m);
  if (!nameMatch) return null;

  // Extract purpose from ## Purpose section
  const purposeMatch = content.match(/^##\s+Purpose\s*\n(.+)$/m);
  const purpose = purposeMatch ? purposeMatch[1].trim() : "No description.";

  return { name: nameMatch[1].trim(), purpose };
}

/**
 * Reads all 2nd-level CONTEXT.md files (i.e. <root>/<category>/<service>/CONTEXT.md),
 * extracts name/purpose/location, groups by category, and returns a markdown table.
 */
export async function generateServiceIndex(root: string): Promise<string> {
  const entries: ServiceEntry[] = [];

  let topDirs: string[];
  try {
    const dirents = await readdir(root, { withFileTypes: true });
    topDirs = dirents
      .filter(d => d.isDirectory() && !d.name.startsWith(".") && d.name !== "node_modules")
      .map(d => d.name);
  } catch {
    topDirs = [];
  }

  for (const category of topDirs) {
    const categoryPath = join(root, category);
    let subDirs: string[];
    try {
      const dirents = await readdir(categoryPath, { withFileTypes: true });
      subDirs = dirents
        .filter(d => d.isDirectory() && !d.name.startsWith(".") && d.name !== "node_modules")
        .map(d => d.name);
    } catch {
      continue;
    }

    for (const service of subDirs) {
      const contextPath = join(categoryPath, service, "CONTEXT.md");
      try {
        const content = await readFile(contextPath, "utf-8");
        const parsed = parseContextMd(content);
        if (parsed) {
          entries.push({
            name: parsed.name,
            purpose: parsed.purpose,
            location: `${category}/${service}`,
            category,
          });
        }
      } catch {
        // No CONTEXT.md in this directory — skip
      }
    }
  }

  // Group by category
  const grouped = new Map<string, ServiceEntry[]>();
  for (const entry of entries) {
    const list = grouped.get(entry.category) || [];
    list.push(entry);
    grouped.set(entry.category, list);
  }

  // Sort categories and entries within each category
  const sortedCategories = [...grouped.keys()].sort();

  const lines: string[] = [
    "# Service Index",
    "",
    "> Auto-generated by Contextador. Do not edit manually.",
    "",
  ];

  for (const category of sortedCategories) {
    const categoryEntries = grouped.get(category)!;
    categoryEntries.sort((a, b) => a.name.localeCompare(b.name));

    lines.push(`## ${category}`);
    lines.push("");
    lines.push("| Service | Location | Purpose |");
    lines.push("|---------|----------|---------|");

    for (const entry of categoryEntries) {
      lines.push(`| ${entry.name} | \`${entry.location}\` | ${entry.purpose} |`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generates the service index and writes it to docs/service-index.md.
 */
export async function syncServiceIndex(root: string): Promise<void> {
  const content = await generateServiceIndex(root);
  const docsDir = join(root, "docs");
  await mkdir(docsDir, { recursive: true });
  await writeFile(join(docsDir, "service-index.md"), content, "utf-8");
}

interface DepEntry {
  name: string;
  location: string;
  category: string;
  upstream: string;
  downstream: string;
}

const DEPS_START = "<!-- CONTEXTADOR:DEPS:START -->";
const DEPS_END = "<!-- CONTEXTADOR:DEPS:END -->";

/**
 * Parse a CONTEXT.md for dependency info (upstream/downstream lines).
 */
function parseDeps(content: string): { upstream: string; downstream: string } | null {
  const upMatch = content.match(/^\s*-\s*\*\*Upstream:\*\*\s*(.+)$/m);
  const downMatch = content.match(/^\s*-\s*\*\*Downstream:\*\*\s*(.+)$/m);
  if (!upMatch && !downMatch) return null;
  return {
    upstream: upMatch ? upMatch[1].trim() : "None",
    downstream: downMatch ? downMatch[1].trim() : "None",
  };
}

/**
 * Reads all 2nd-level CONTEXT.md files and extracts dependency info,
 * returning a markdown table grouped by category.
 */
export async function generateDepsSection(root: string): Promise<string> {
  const entries: DepEntry[] = [];

  let topDirs: string[];
  try {
    const dirents = await readdir(root, { withFileTypes: true });
    topDirs = dirents
      .filter(d => d.isDirectory() && !d.name.startsWith(".") && d.name !== "node_modules")
      .map(d => d.name);
  } catch {
    topDirs = [];
  }

  for (const category of topDirs) {
    const categoryPath = join(root, category);
    let subDirs: string[];
    try {
      const dirents = await readdir(categoryPath, { withFileTypes: true });
      subDirs = dirents
        .filter(d => d.isDirectory() && !d.name.startsWith(".") && d.name !== "node_modules")
        .map(d => d.name);
    } catch {
      continue;
    }

    for (const service of subDirs) {
      const contextPath = join(categoryPath, service, "CONTEXT.md");
      try {
        const content = await readFile(contextPath, "utf-8");
        const parsed = parseContextMd(content);
        const deps = parseDeps(content);
        if (parsed && deps) {
          entries.push({
            name: parsed.name,
            location: `${category}/${service}`,
            category,
            upstream: deps.upstream,
            downstream: deps.downstream,
          });
        }
      } catch {
        // No CONTEXT.md or unreadable — skip
      }
    }
  }

  // Group by category
  const grouped = new Map<string, DepEntry[]>();
  for (const entry of entries) {
    const list = grouped.get(entry.category) || [];
    list.push(entry);
    grouped.set(entry.category, list);
  }

  const sortedCategories = [...grouped.keys()].sort();

  const lines: string[] = [
    DEPS_START,
    "",
    "### Service Dependency Map",
    "",
    "> Auto-generated by Contextador. Do not edit manually.",
    "",
  ];

  for (const category of sortedCategories) {
    const categoryEntries = grouped.get(category)!;
    categoryEntries.sort((a, b) => a.name.localeCompare(b.name));

    lines.push(`#### ${category}`);
    lines.push("");
    lines.push("| Service | Location | Upstream | Downstream |");
    lines.push("|---------|----------|----------|------------|");

    for (const entry of categoryEntries) {
      lines.push(`| ${entry.name} | \`${entry.location}\` | ${entry.upstream} | ${entry.downstream} |`);
    }

    lines.push("");
  }

  lines.push(DEPS_END);

  return lines.join("\n");
}

/**
 * Syncs the dependency map section in docs/architecture.md.
 * Replaces content between CONTEXTADOR:DEPS markers, or appends if markers are absent.
 */
export async function syncArchitectureDeps(root: string): Promise<void> {
  const docsDir = join(root, "docs");
  await mkdir(docsDir, { recursive: true });
  const archPath = join(docsDir, "architecture.md");

  const depsSection = await generateDepsSection(root);

  let existing: string;
  try {
    existing = await readFile(archPath, "utf-8");
  } catch {
    // No architecture.md — create one with just the deps section
    await writeFile(archPath, `# Architecture\n\n${depsSection}\n`, "utf-8");
    return;
  }

  const startIdx = existing.indexOf(DEPS_START);
  const endIdx = existing.indexOf(DEPS_END);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace between markers (inclusive)
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + DEPS_END.length);
    await writeFile(archPath, before + depsSection + after, "utf-8");
  } else {
    // Append markers at end
    const separator = existing.endsWith("\n") ? "\n" : "\n\n";
    await writeFile(archPath, existing + separator + depsSection + "\n", "utf-8");
  }
}
